version: '3.2'

services:

  nginx:
    restart: always
    build: ./user-nginx/
    ports:
      - "80:80"
    networks:
      - web
    links:
      - swaggerui

  swaggerui:
    build: swagger-ui
    networks:
      - web
    expose:
      - "5000"
    ports:
      - 5000:5000

networks:
  web:
    external: true
