version: '3.2'

services:

  nginx:
    restart: always
    build: ./user-nginx/
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - web
    links:
      - swaggerui
      - falconswagger

  falconswagger:
    build: falcon-swagger
    networks:
      - web
    expose:
      - "8000"

  swaggerui:
    build: swagger-ui
    networks:
      - web
    expose:
      - "5000"

networks:
  web:
    external: true
